# Generated by Django 4.0.2 on 2022-02-14 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersdata',
            name='userid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
