# Generated by Django 4.0.2 on 2022-02-14 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0002_usersdata_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersdata',
            name='desc',
            field=models.TextField(default=0, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usersdata',
            name='title',
            field=models.TextField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
