# Generated by Django 4.0.2 on 2022-02-14 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0003_usersdata_desc_usersdata_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersdata',
            name='userid',
            field=models.CharField(max_length=100),
        ),
    ]
