# Generated by Django 4.0.2 on 2022-02-14 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0004_alter_usersdata_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersdata',
            name='userid',
        ),
    ]
